### ISSUE TITLE
Confirmation: Multiple classes possible simultaneously

### ISSUE THREAD

**Issue by RylanSchaeffer** [askerlee/segtran#10]
Quick question regarding the following line:

https://github.com/askerlee/segtran/blob/master/code/train3d.py#L695

The tensor passed to sigmoid has shape `(batch size, num classes, H, W, D)`. Because the sigmoid is applied element-wise, this suggests to me that the classes are **not** competitive. By this I mean, multiple classes can exist simultaneously. Can you confirmation that this is correct?

Thanks in advance!

**Comment by askerlee** [comment]
Yes your understanding is correct. I remember it performs slightly better than letting multiple classes compete with each other, both on 2D and 3D images.

**Comment by RylanSchaeffer** [comment]
Thank you!
