### ISSUE TITLE
error on testing

### ISSUE THREAD

**Issue by Ema-Rachmawati** [askerlee/segtran#14]
Hi askerlee, 

I've tried your project with a small amount of images: 10 images. 

Could you help me with this error?

![error_test](https://user-images.githubusercontent.com/84435600/133210557-5f3d7b8c-962a-44e8-89d3-bbe9ed97fc87.png)

Thanks!

**Comment by askerlee** [comment]
Oh this is calling "zip" to compress the result masks into a .zip file, so that you can easily move the results to another PC or submit to a challenge website. You could ignore this error. I'll update the script, so that if it doesn't find "zip", it just prints a warning.

**Comment by askerlee** [comment]
Revised now. Thank you for your feedback!
