### ISSUE TITLE
how to test the model during training

### ISSUE THREAD

**Issue by wshi8** [askerlee/segtran#15]
Hi Dr. Lee,

Is test/validation implemented during model training? I want to test/validate the ongoing performance during training but did not figure out how to do that from the code. I did see that there are three data files( all.list, train.list and test.list), wondering how to test and report the perf info during training.

Best
Wendy

**Comment by askerlee** [comment]
I didn't implement it, as two of the major experiments are challenges, and we are unable to evaluate until we submit the results to challenge websites.  But you can manually run test2d.py/test3d.py separately to evaluate on your validation data.

**Comment by wshi8** [comment]
I tried to run it for a set of 110 test images a few times, but it somehow always exit around 70-ish images without any error, and never successfully finished the 110 images.
