### ISSUE TITLE
test3d.py failure

### ISSUE THREAD

**Issue by wshi8** [askerlee/segtran#16]
Hi Dr Lee,

I tried to run test3d.py for a set of 110 test images a few times, but it somehow always exit unexpectedly around 70-ish images without any error. So far, I have never successfully finished the 110 images.

Any advice?

Best,
Wendy

**Comment by askerlee** [comment]
This is weird. I never experienced such problems (I've run segtran on different computers). Could you check whether your CUDA version is not too old, and the pytorch installed matches your CUDA version?
