### ISSUE TITLE
how to test on other brats dataset such as 2020?

### ISSUE THREAD

**Issue by bhralzz** [askerlee/segtran#18]
Hi dear Askerlee,
first of all, greetin for your valuable code,
please explain how I can test this code over brats 2020 dataset,
as I replace that dataset in the brats path also setting the parameters in the train3d.py, but the .h5 files were not exist in the cases pathes.
waiting to hear from you,
thanks

**Comment by askerlee** [comment]
Sorry I've added how to do data preparation in README. Thanks for raising this up.

**Comment by bhralzz** [comment]
I checked your files,
1- it seems to start with brats_processing.py in dataloader, yeah?
2- is there any further action need?
3- So when you can add that guide  in readme file?

**Comment by askerlee** [comment]
The short guide is here:
https://github.com/askerlee/segtran/blob/master/README.md#data-preparation
After that, please create a symbolic link from the generated h5 folder to data/brats/your_h5_folder_name, and add the dataset meta-info into train3d.py/test3d.py. 
Is there anything else you are feeling not very clear?

**Comment by bhralzz** [comment]
yes I tested that,
but as you know the validations have not seg files, so the second command for validation processing go in error.

**Comment by askerlee** [comment]
If "validation" (case insensitive) is part of the folder name, then it doesn't look for segmentation masks. Maybe your folder is not named as such?

**Comment by bhralzz** [comment]
Absolutely,
checking this in the folder name resolved  that error,
I am going to check enter train/test process.
Thanks for kind reply, helpfull.

**Comment by askerlee** [comment]
Sorry this was made unnecessarily tricky 😅 Maybe I should use use a command line argument instead

**Comment by bhralzz** [comment]
> Sorry this was made unnecessarily tricky 😅 Maybe I should use a command line argument instead

**Comment by bhralzz** [comment]
Hi again.
I also tested the multi gpu form and worked fine till now,
however I need to use trained model for testing on new samples.
did you tested test.py files?
Error shown as below
TypeError: __init__() got an unexpected keyword argument 'mask_num_classes'

please check test.py

thanks
