### ISSUE TITLE
Brats iter-8000 checkpoint is not loading on test

### ISSUE THREAD

**Issue by wshi8** [askerlee/segtran#21]
Hi Dr Lee,

I got this error when I tried to run the test command using your recently updated Brats iter_8000 checkpoint, any advice?

 python3 test3d.py --task brats --split all --bs 5 --ds 2019valid --net segtran --attractors 1024 --translayers 1 --cpdir ./ --iters 8000

Traceback (most recent call last):
  File "test3d.py", line 426, in <module>
    allcls_avg_metric = test_calculate_metric(iter_nums)
  File "test3d.py", line 350, in test_calculate_metric
    load_model(net, args, checkpoint_path)
  File "test3d.py", line 311, in load_model
    if (k not in ignored_keys) and (args2.__dict__[k] != cp_args[k]):
KeyError: 'qk_have_bias'

The Error is on "load_model(net, args, checkpoint_path)" in the following:

    for iter_num in iter_nums:
        if args.checkpoint_dir:
            checkpoint_path = os.path.join(args.checkpoint_dir, 'iter_' + str(iter_num) + '.pth')
            load_model(net, args, checkpoint_path)

**Comment by wshi8** [comment]
I would like to find out "sensitivity" and "fp_per_case" for the Brats data set, if you happen to have that, that would help a lot

**Comment by askerlee** [comment]
[Stats_Validation_final-09190053-8000.csv](https://github.com/askerlee/segtran/files/7215729/Stats_Validation_final-09190053-8000.csv)

This is the result file downloaded from the challenge evaluation server. There are a few columns of "sensitivity" but I didn't find "fp_per_case".

**Comment by askerlee** [comment]
The error "KeyError: 'qk_have_bias'" should disappear after you update the code to the newest. Thanks.
