### ISSUE TITLE
about calling test from another file.py

### ISSUE THREAD

**Issue by bhralzz** [askerlee/segtran#22]
Hi
Dear Shaohua

is there any part of this code to set just trained model path  and new sample pathe from out file.oy then getting result by these parameters without going into args parsing?

**Comment by askerlee** [comment]
I guess you mean this function call? 😃 

https://github.com/askerlee/segtran/blob/729b54c9d3ad05a0d97cb3cc3e81f171b3f39354/code/test3d.py#L355

**Comment by bhralzz** [comment]
actually 
I saw this before,
But as you can see its require that we set arguments as  commandline parameter,
So is there a way to call this function with minimal parameters without commandline parameters?

**Comment by askerlee** [comment]
Uh I've thought about the arguments and seems most of them are necessary, except test_interp, which is usually False. This is to give the caller the most flexibility to tune under different settings. So I guess there isn't much simplification to be done. 

Above all, the arguments are not coupled with args. They just happen to take values from args in this instance.

**Comment by bhralzz** [comment]
OK,
Thanks
