### ISSUE TITLE
Baseline comparison for 2D dataset

### ISSUE THREAD

**Issue by wshi8** [askerlee/segtran#25]
Hi Dr. Lee, do you have the code that you used to compare with various baselines in section 5.2 (list of other models) for 2D dataset?  Is there a similar comparison for the 3D dataset?

**Comment by askerlee** [comment]
Yes all the baseline code is included in this repo. You just need to provide different --net parameters. For example, 'unet-scratch' for vanilla u-net, 'unet' for using pretrained encoders (--bb eff-b4 to use efficientnet-b4 as the encoder).

**Comment by askerlee** [comment]
For 3D images, only Unet-3D and V-Net were included in the code. There are two more baselines in the paper, whose results were extracted from their papers.

**Comment by askerlee** [comment]
I see. In test3d.py, the input channels of V-Net / U-Net 3d are hardcoded as 1. You could try to change it to 2 and see what you can get.

**Comment by wshi8** [comment]
Thanks! Is there or Do I need to upload any checkpoint for the U-net/V-net 3D t for testing?
