### ISSUE TITLE
About the index out of range

### ISSUE THREAD

**Issue by 15104356116** [askerlee/segtran#28]
Hello! Sorry to bother u. I've just git the project down on the colab. And I upload 13 images and masks of the dataset, CVC-300, to the project. But when I run the main.py, it shows that:
Epoch : 1
3/3 [==============================] - 23s 2s/step - loss: 0.6957 - dice_coef: 0.2971 - jacard: 0.1746 - accuracy: 0.5558
1/1 [==============================] - 4s 4s/step
Traceback (most recent call last):
  File "main.py", line 234, in <module>
    trainStep(model, X_train, Y_train, X_test, Y_test, epochs=150, batchSize=4)
  File "main.py", line 216, in trainStep
    evaluateModel(model,X_test, Y_test,batchSize)
  File "main.py", line 147, in evaluateModel
    plt.imshow(X_test[i])
IndexError: index 3 is out of bounds for axis 0 with size 3
I have no idea how to deal with that.
Hope you can help me with that. So sorry to bother you.🙏🙏🙏

**Comment by askerlee** [comment]
Seems this code is not from segtran project? There's no such lines in this project. From what you just posted, I cannot tell where the bug may be.

**Comment by 15104356116** [comment]
OMG! Thank you for your reply, I'll check the code. So sorry to bother you.
