### ISSUE TITLE
hardware

### ISSUE THREAD

**Issue by mahdiyehbakhshi822** [askerlee/segtran#34]
hi
Thanks for the great project
What is the hardware required to run the code?
And what is the approximate running time?

**Comment by askerlee** [comment]
It all depends on the image resolution and whether it's 2d or 3d.
For example on 200-300 pixel images, the training usually takes a few hours
on popular GPUs, such as RTX3090, Titan X or A6000/3000. Typically, the RAM
cost will be 10-20GB. For 3D images the RAM consumption could be much
higher.
