### ISSUE TITLE
about ModuleNotFoundError

### ISSUE THREAD

**Issue by Lemonweier** [askerlee/segtran#38]
Hi，sir. I move the project to the new computer.  I meet `ModuleNotFoundError: No module named 'networks.segtran2d'`.It would have been nice if you had given me a hint. Thank u!

**Comment by askerlee** [comment]
This is weird. Do you put them in the correct directory, and execute with python3 at the "code" folder?

**Comment by Lemonweier** [comment]
您发给我的邮件已收到，谢谢！

**Comment by Lemonweier** [comment]
The method of execution is the same as before. You mention the correct directory,what is it mean.And I check the environment `pip list`has networks package.

**Comment by askerlee** [comment]
"networks" is the networks folder in my github repo. It shouldn't be installed through pip:
https://github.com/askerlee/segtran/tree/master/code/networks

**Comment by Lemonweier** [comment]
You are right sir. I use` pip uninstall` this weird package. It works!Thank u very much.

**Comment by askerlee** [comment]
Great to know it's solved.
