### ISSUE TITLE
Question of brats_processing.py useage

### ISSUE THREAD

**Issue by sherjy** [askerlee/segtran#4]
Hiiii askerlee! Thanks for your nice work and repo!!
I have a question for how to use brats_processing.py to process my brats19 or 20 dataset.
After reading the codes, I do sth like this for train and val dataset respectively:
~~~
python3 brats_processing.py h5 brats_trainset_root
python3 brats_processing.py label brats_valset_root
~~~
Is this usage right since label process seems no affects to data? I'm confused of what **python3 brats_processing.py label brats_valset_root** really does.

**Comment by askerlee** [comment]
Hi @sherjy , python3 brats_processing.py label label_file is only computing statistics of the label files (shape and non-zero percentages); it does nothing else. To preprocess your brats MRI files, you can use python3 brats_processing.py h5 brats_trainset_root. 

Hope this clarifies.

**Comment by sherjy** [comment]
Thanks for your quick reply!! It's clear now.

> Hi @sherjy , `python3 brats_processing.py label label_file` is only computing statistics of the label files (shape and non-zero percentages); it does nothing else. To preprocess your brats MRI files, you can use `python3 brats_processing.py h5 brats_trainset_root`.
> 
> Hope this clarifies.
