### ISSUE TITLE
chechpoint

### ISSUE THREAD

**Issue by mahdiyehbakhshi822** [askerlee/segtran#42]
hi
Thank you for great code
How can check points be accessed? I will be grateful if you provide me with the Google Drive link

**Comment by askerlee** [comment]
Thanks for your interest!
The checkpoints on fundus dataset, and brats dataset can be downloaded at:
https://www.dropbox.com/sh/xjqhqqhbfd44nmo/AAADg0NcCDi1ayWljCJwqKi8a?dl=0
