### ISSUE TITLE
Problem about the mask of RIM dataset

### ISSUE THREAD

**Issue by Yongze** [askerlee/segtran#44]
In REFUGE dataset, the pixel in each channel of the mask can be like this:
channel 0 ---> {0: 243058, 255: 88718}
channel 1 ---> {0: 294881, 255: 36895}
channel 2 ---> {0: 331776}
It means the mask values can be either 1 or 255. ("key: is the pixel value, "value" is the number of pixels with that value)

BUT in RIM dataset, the pixel value in each channel of the mask can be:
channel 0 ---> {0: 281893, 138: 27, 158: 84, 98: 20, 222: 84, 250: 13, 254: 480, 242: 37, 221: 31, 3: 13, 31: 72, 114: 17, 253: 66, 255: 48551, 225: 21, 19: 21, 35: 13, 95: 61, 115: 9, 194: 26, 83: 39, 27: 29, 233: 21, 59: 49, 218: 17, 11: 23, 94: 5, 154: 10, 170: 21, 193: 13, 234: 6, 226: 4}
channel 1 ---> {0: 318085, 11: 14, 31: 42, 35: 10, 95: 46, 154: 7, 254: 248, 253: 42, 98: 10, 158: 44, 194: 14, 255: 12965, 193: 9, 222: 29, 242: 18, 221: 16, 27: 17, 59: 27, 170: 15, 233: 13, 138: 15, 218: 9, 19: 12, 83: 21, 250: 9, 225: 7, 94: 3, 114: 7, 3: 8, 234: 2, 226: 6, 115: 6}
channel 2 ---> {0: 331776}

We can see that the mask values in rim dataset can be any int between 0 and 255. My question is, how to deal with this?
For example, can we treat any value > 0 would be the target and == 0 will be the background?

**Comment by askerlee** [comment]
I remember I treated all non-zero pixels as 255. It's been a long time and my memory is quite rusty. But my impression is that the exact value T you choose to threshold the pixel values (>=T as foreground, <T as background) doesn't matter much, as the intermediate pixels only take a small proportion of the whole image, so it won't lead to noticeable change to the evaluation results.

**Comment by Yongze** [comment]
OK, I see. Thanks for the reply
