### ISSUE TITLE
atria error

### ISSUE THREAD

**Issue by wshi8** [askerlee/segtran#5]
Hello, thank you for all the wonderful project. I tried to run the atria task and got the following error, any advice? 

 python3 train3d.py --task atria --split all --bs 2 --maxiter 10000 --randscale 0.1 --net segtran --attractors 1024 --translayers 1

Traceback (most recent call last):
  File "train3d.py", line 549, in <module>
    xyz_permute=args.xyz_permute)
TypeError: __init__() got an unexpected keyword argument 'mask_num_classes'

**Comment by askerlee** [comment]
Sorry I'm busy working on the GAMMA challenge these days. Will check the code as soon as I have some free time.
