### ISSUE TITLE
Are checkpoints of this model available?

### ISSUE THREAD

**Issue by MengzhangLI** [askerlee/segtran#6]
Hi, thanks for your excellent work!

I want to re-implement this model, will you provide your trained models whose results achieve SOTA from your paper? Thus we can only use your model doing inference.

Especially model on REFUGE and BraTS, segtran is very extraordinary.

Best,

**Comment by askerlee** [comment]
Sure I'll be happy to share the checkpoints. Lemme check whether they are still on my harddisk. If not, I'll do a retraining.

**Comment by RylanSchaeffer** [comment]
@askerlee any updates? :D

**Comment by askerlee** [comment]
@RylanSchaeffer I uploaded a checkpoint for REFUGE to baidu netdisk: 
URL: https://pan.baidu.com/s/1TmV27ziwrULGa0KFA2ohuQ 
code: qsll 

The problem is it's too big (around 1G). I haven't checked why it's so big.
It achieves 0.959/0.870 on REFUGE leaderboard.

**Comment by wshi8** [comment]
@askerlee Thank you for loading the model, would you please also upload the trained model checkpoint for the BraTS? I am looking into using the 3D model for the BraTS dataset

**Comment by askerlee** [comment]
I've deleted the checkpoint but I'll retrain it today. Probably will be able to upload it tomorrow.

**Comment by wshi8** [comment]
Thank you @askerlee

**Comment by askerlee** [comment]
@wshi8 The checkpoints on BraTS 2019 and REFUGE 2020 have been uploaded to: 
https://pan.baidu.com/s/1nbBrPJKK1NtOe848cApS8w 
code: h1vi 

On BraTS 2019 validation:
0.729/0.896/0.832, Avg. 0.819 
On REFUGE 2020 validation:
0.870/0.959, Avg. 0.915

**Comment by wshi8** [comment]
Thanks a lot! what is the 3 value number corresponding to? is this "Accuracy" for 3 validation runs?
0.729/0.896/0.832, Avg. 0.819

**Comment by askerlee** [comment]
@wshi8 They are the dice scores of ET (enhancing tumor), WT (whole tumor) and TC (tumor core), just as the metrics reported in my ijcai paper.
