### ISSUE TITLE
Confirmation Question: Input to Model?

### ISSUE THREAD

**Issue by RylanSchaeffer** [askerlee/segtran#9]
Hi! Quick question: what is the actual input to the network? Is the input the full 2D/3D image, or is the input smaller (perhaps random) sections of the full image?

I think the answer is the full image, but I want to confirm.

**Comment by RylanSchaeffer** [comment]
Ok maybe input images are cropped first, based on this line

https://github.com/askerlee/segtran/blob/master/code/train3d.py#L528

Could you clarify?

**Comment by askerlee** [comment]
Correct. It's randomly cropped during training to reduce overfitting. Otherwise the model always sees the same image and easily remembers the correct mask.

**Comment by RylanSchaeffer** [comment]
Thank you!
